# Generated by Django 5.2.1 on 2025-06-05 18:25

import django.core.validators
import validate_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=250, validators=[validate_app.models.startwith_capital, django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
